import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Meteors } from "@/components/ui/meteors";
import { ScrollProgress } from "@/components/ui/scroll-progress";
import { FaFacebook, FaGithub, FaInstagram, FaLinkedinIn, FaTwitter } from "react-icons/fa";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
      >
        <ScrollProgress className="top-[0px]" />
        <Meteors number={15} />
        {children}
        <div className="fixed right-0 top-1/2 transform -translate-y-1/2 z-50">
          <div className="flex flex-col gap-4 bg-white p-2 rounded-l-lg shadow-lg">
            <a
              href="https://www.facebook.com/your-profile"
              target="_blank"
              rel="noopener noreferrer"
              className="transform transition duration-300 ease-in-out hover:scale-110 hover:text-blue-600"
            >
              <FaFacebook size={24} color="#4267B2" />
            </a>
            <a
              href="https://twitter.com/your-handle"
              target="_blank"
              rel="noopener noreferrer"
              className="transform transition duration-300 ease-in-out hover:scale-110 hover:text-blue-400"
            >
              <FaTwitter size={24} color="#1DA1F2" />
            </a>
            <a
              href="https://www.instagram.com/your-handle"
              target="_blank"
              rel="noopener noreferrer"
              className="transform transition duration-300 ease-in-out hover:scale-110 hover:text-pink-500"
            >
              <FaInstagram size={24} color="#E1306C" />
            </a>
            <a
              href="https://www.linkedin.com/in/your-profile"
              target="_blank"
              rel="noopener noreferrer"
              className="transform transition duration-300 ease-in-out hover:scale-110 hover:text-blue-700"
            >
              <FaLinkedinIn size={24} color="#0A66C2" />
            </a>
            <a
              href="https://github.com/your-username"
              target="_blank"
              rel="noopener noreferrer"
              className="transform transition duration-300 ease-in-out hover:scale-110 hover:text-gray-700"
            >
              <FaGithub size={24} color="#171515" />
            </a>
          </div>
        </div>

      </body>
    </html>
  );
}
